version: '3'

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: pix-compute-lead-time-postgres
    ports:
      - '${PIX_DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust